import { useState, useEffect } from 'react';
import { useSession, useSupabaseClient, useUser } from '@supabase/auth-helpers-react';
import Head from 'next/head';

// component imports
import ParisTours from '../../components/tours/ParisTours';

// style imports
import styles from '../../styles/Tours.module.css';

const ToursPage = () => {
	const session = useSession();
	const supabase = useSupabaseClient();
	const user = useUser();
	const [franceTour, setFranceTour] = useState([]);

	useEffect(() => {
		async function loadData() {
			const { data, error } = await supabase.from('france_tour').select('*');
			setFranceTour(data);
		}
		// Only run query once user is logged in.
		if (user) loadData();
	}, [supabase, user]);

	return (
		<main className={styles.main}>
			<Head>
				<title>Tours</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{user ? (
				<ParisTours tours={franceTour} />
			) : (
				<p>Not logged in, Please login to see our tours to France</p>
			)}
		</main>
	);
};

export default ToursPage;
