import { useState, useEffect } from 'react';
import { useSession, useSupabaseClient, useUser } from '@supabase/auth-helpers-react';
import Head from 'next/head';

// component imports
import ParisTours from '../../components/tours/ParisTours';

// style imports
import styles from '../../styles/Tours.module.css';
import ScandinaviaTour from '../../components/tours/ScandinaviaTour';

const ToursPage = () => {
	const session = useSession();
	const supabase = useSupabaseClient();
	const user = useUser();
	const [franceTour, setFranceTour] = useState([]);
	const [scandinaviaTour, setScandinaviaTour] = useState([]);

	useEffect(() => {
		async function loadData() {
			const { data, error } = await supabase.from('france_tour').select('*');
			setFranceTour(data);
		}
		async function loadScandinaviaData() {
			const { data, error } = await supabase.from('scandinavia_tour').select('*');

			if (error) {
				console.log(error);
			}

			setScandinaviaTour(data);
		}
		// Only run query once user is logged in.
		loadScandinaviaData();
		loadData();
	}, [supabase, user]);

	return (
		<main className={styles.main}>
			<Head>
				<title>Tours</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ParisTours tours={franceTour} />
			<ScandinaviaTour tours={scandinaviaTour} />
		</main>
	);
};

export default ToursPage;
