import { useState } from 'react';
import Link from 'next/link';
import Head from 'next/head';

//import style modules from styles/forms.module.css
import styles from '../styles/Forms.module.css';

const Signup = ({ supabase }) => {
	const [email, setEmail] = useState('');
	const [username, setUsername] = useState('');
	const [password, setPassword] = useState('');
	const [passwordConfirm, setPasswordConfirm] = useState('');
	const [alert, setAlert] = useState('');
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState('');

	const resetForm = () => {
		setEmail('');
		setUsername('');
		setPassword('');
		setPasswordConfirm('');
		setLoading(false);
		setError('');
	};

	const handleSubmit = async (e) => {
		e.preventDefault();
		setLoading(true);
		setError('');
		if (password !== passwordConfirm) {
			setError('Passwords do not match');
			setLoading(false);
			return;
		}
		const { user, error } = await supabase.auth.signUp({
			email,
			password,
			options: {
				data: {
					username,
				},
			},
		});

		if (error) {
			console.log(error);
			setLoading(false);
			setError(error.message);
		} else {
			resetForm();
			setAlert('Check your email for the confirmation link');
		}
	};

	return (
		<>
			<Head>
				<title>Student Travel- signup</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1>Signup</h1>
				{alert && <p>{alert}</p>}
				{error && <p>{error}</p>}
				<h2>Please create an account to book a tour</h2>
				<form onSubmit={handleSubmit}>
					<label className={styles.label} htmlFor="email">
						Email
					</label>
					<input
						className={styles.input}
						type="email"
						id="email"
						value={email}
						onChange={(e) => setEmail(e.target.value)}
					/>
					<label className={styles.label} htmlFor="username">
						Username
					</label>
					<input
						className={styles.input}
						type="text"
						id="username"
						value={username}
						onChange={(e) => setUsername(e.target.value)}
					/>

					<label className={styles.label} htmlFor="password">
						Password
					</label>
					<input
						className={styles.input}
						type="password"
						id="password"
						value={password}
						onChange={(e) => setPassword(e.target.value)}
					/>
					<label className={styles.label} htmlFor="passwordConfirm">
						Confirm Password
					</label>
					<input
						className={styles.input}
						type="password"
						id="passwordConfirm"
						value={passwordConfirm}
						onChange={(e) => setPasswordConfirm(e.target.value)}
					/>

					<button className={styles.button} type="submit" disabled={loading}>
						{loading ? 'Loading...' : 'Signup'}
					</button>
				</form>
				<p>
					Already have an account?{' '}
					<Link href="/login" style={{ textDecoration: 'underline' }}>
						Login
					</Link>
				</p>
				{error && <p>{error}</p>}
			</main>
		</>
	);
};

export default Signup;
