import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';

// component imports
import Signup from '../components/Signup';

// style imports

export default function Home() {
	const session = useSession();
	const supabase = useSupabaseClient();

	return (
		<div className={styles.container}>
			<Head>
				<title>Student Travel</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{!session ? <Signup supabase={supabase} /> : <p>HomePage Content here</p>}
		</div>
	);
}
